language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
install: bash ./coverage/install-dependencies.sh
script: pytest tests/ --cov=moniter_bus --cov-report xml:cov.xml
after_failure: false
after_success: bash <(curl -s https://codecov.io/bash) -t 0ef97c01-4076-4e96-81e8-c0bb0aed0541