language: python
install: bash ./coverage/install-dependencies.sh
script: pytest tests/ --cov=moniter_bus --cov-report xml:cov.xml
after_success: bash <(curl -s https://codecov.io/bash) -t 0ef97c01-4076-4e96-81e8-c0bb0aed0541